In [5]:
import numpy as np

In [6]:
list=[0,1,2,3,4,5]
list

[0, 1, 2, 3, 4, 5]

In [7]:
type(list)

list

In [8]:
arr=np.array(list)
arr

array([0, 1, 2, 3, 4, 5])

In [9]:
type(arr)

numpy.ndarray

In [11]:
np.random

<module 'numpy.random' from 'C:\\Users\\Shaik Mahimood\\anaconda3\\Lib\\site-packages\\numpy\\random\\__init__.py'>

In [12]:
np.random.rand(4)

array([0.41660441, 0.22242239, 0.9815024 , 0.60200442])

In [13]:
np.random.rand(2,4)

array([[0.57161192, 0.5422038 , 0.01849815, 0.7881564 ],
       [0.00848523, 0.22507129, 0.80713989, 0.99299224]])

In [14]:
np.random.rand(1,5)

array([[0.24076214, 0.22481098, 0.08374881, 0.01497639, 0.91491814]])

In [15]:
np.random.rand(8,9)

array([[0.19222769, 0.64714738, 0.63496305, 0.69027973, 0.39387441,
        0.63318256, 0.37618206, 0.20144109, 0.37261508],
       [0.4344263 , 0.75309411, 0.1872971 , 0.24675683, 0.45571417,
        0.89062426, 0.11975828, 0.13734754, 0.11671061],
       [0.16373386, 0.64180742, 0.55785694, 0.23273402, 0.26103828,
        0.03195488, 0.05597532, 0.79828506, 0.0173754 ],
       [0.21008514, 0.40542398, 0.64916341, 0.01225627, 0.95939843,
        0.67122196, 0.7486371 , 0.00891838, 0.53701043],
       [0.39795088, 0.85614622, 0.16346943, 0.96804369, 0.87337456,
        0.13322419, 0.36948135, 0.61983229, 0.7967681 ],
       [0.87338943, 0.83687907, 0.26014483, 0.00965077, 0.61591816,
        0.32207441, 0.84589214, 0.21684457, 0.34642933],
       [0.07570616, 0.87449223, 0.75158299, 0.18445478, 0.76300071,
        0.66934561, 0.79241864, 0.93961381, 0.95153899],
       [0.55992085, 0.88317239, 0.69479639, 0.51976199, 0.34444494,
        0.00414102, 0.97249212, 0.35876786, 0.12313423]])

In [19]:
np.random.randint(2,20)

11

In [20]:
np.random.randint(5,88)

74

In [22]:
np.random.randint(55,56)

55

In [24]:
np.random.randint(1,10,3)

array([6, 5, 1])

In [25]:
np.random.randint(1,20,6)

array([18, 17, 14,  8, 15, 18])

In [26]:
np.random.randint(10,30,7)

array([16, 12, 16, 21, 23, 13, 25])

In [27]:
np.random.randint(1,12,10)

array([ 1, 10,  8,  2,  4,  9,  6,  7,  2,  4])

In [28]:
np.random.randint(1,5,6)

array([1, 3, 1, 2, 3, 3])

In [30]:
np.random.randint(1,20,(5,5))

array([[ 9,  4,  2, 15, 11],
       [11, 17, 11, 15, 10],
       [14, 16, 10,  9, 16],
       [15, 14,  8,  9, 12],
       [ 2, 19,  7, 16, 16]])

In [31]:
np.random.randint(10,25,(6,7))

array([[20, 11, 16, 22, 11, 12, 13],
       [20, 24, 17, 18, 10, 20, 19],
       [19, 19, 12, 21, 19, 18, 16],
       [21, 17, 23, 23, 22, 14, 23],
       [15, 24, 24, 21, 16, 11, 19],
       [15, 23, 18, 21, 21, 10, 13]])

In [34]:
b=np.random.randint(10,20,(5,4))
b

array([[18, 11, 13, 11],
       [15, 14, 14, 15],
       [18, 15, 11, 17],
       [19, 16, 17, 12],
       [17, 11, 13, 16]])

In [35]:
b[:]

array([[18, 11, 13, 11],
       [15, 14, 14, 15],
       [18, 15, 11, 17],
       [19, 16, 17, 12],
       [17, 11, 13, 16]])

In [36]:
b[0:2]

array([[18, 11, 13, 11],
       [15, 14, 14, 15]])

In [37]:
b[:2]

array([[18, 11, 13, 11],
       [15, 14, 14, 15]])

In [38]:
b[2:]

array([[18, 15, 11, 17],
       [19, 16, 17, 12],
       [17, 11, 13, 16]])

In [39]:
b[2:4]

array([[18, 15, 11, 17],
       [19, 16, 17, 12]])

In [40]:
b[:-1]

array([[18, 11, 13, 11],
       [15, 14, 14, 15],
       [18, 15, 11, 17],
       [19, 16, 17, 12]])

In [41]:
b[:-2]

array([[18, 11, 13, 11],
       [15, 14, 14, 15],
       [18, 15, 11, 17]])

In [42]:
b[:-3]

array([[18, 11, 13, 11],
       [15, 14, 14, 15]])

In [45]:
b[::-1]

array([[17, 11, 13, 16],
       [19, 16, 17, 12],
       [18, 15, 11, 17],
       [15, 14, 14, 15],
       [18, 11, 13, 11]])

In [52]:
b[::2]

array([[18, 11, 13, 11],
       [18, 15, 11, 17],
       [17, 11, 13, 16]])

In [51]:
b[::3]

array([[18, 11, 13, 11],
       [19, 16, 17, 12]])

In [54]:
b

array([[18, 11, 13, 11],
       [15, 14, 14, 15],
       [18, 15, 11, 17],
       [19, 16, 17, 12],
       [17, 11, 13, 16]])

In [55]:
b[0,2]

13

In [57]:
b[2,3]

17

In [58]:
b[-1,3]

16

In [60]:
b[-2,-3]

16

In [61]:
b[-3,2]

11

In [62]:
b[:3]

array([[18, 11, 13, 11],
       [15, 14, 14, 15],
       [18, 15, 11, 17]])

In [63]:
b[3:]

array([[19, 16, 17, 12],
       [17, 11, 13, 16]])

In [66]:
arr2=np.random.randint(0,80,(10,10))
arr2

array([[22, 22, 48, 70,  3, 37, 68, 57, 58, 66],
       [22,  2, 32, 76, 45, 47, 63, 78,  1, 44],
       [26, 63, 15, 73, 27, 62, 46, 32, 37, 43],
       [35, 43, 72, 79, 56, 44, 26, 18, 56, 23],
       [37, 67, 51,  5, 71, 30,  0, 58, 28, 61],
       [54, 29,  3, 45, 62, 27, 78, 24, 21, 69],
       [74, 62, 70, 29, 12, 68, 29, 70, 33, 63],
       [47, 41, 56, 39, 46, 23, 69,  6, 71, 78],
       [31,  8, 20, 52, 32, 12,  5, 54, 63, 53],
       [65, 35, 62, 44, 23, 78, 22,  6, 52, 74]])

In [67]:
arr2[:4]

array([[22, 22, 48, 70,  3, 37, 68, 57, 58, 66],
       [22,  2, 32, 76, 45, 47, 63, 78,  1, 44],
       [26, 63, 15, 73, 27, 62, 46, 32, 37, 43],
       [35, 43, 72, 79, 56, 44, 26, 18, 56, 23]])

In [68]:
arr2[4:]

array([[37, 67, 51,  5, 71, 30,  0, 58, 28, 61],
       [54, 29,  3, 45, 62, 27, 78, 24, 21, 69],
       [74, 62, 70, 29, 12, 68, 29, 70, 33, 63],
       [47, 41, 56, 39, 46, 23, 69,  6, 71, 78],
       [31,  8, 20, 52, 32, 12,  5, 54, 63, 53],
       [65, 35, 62, 44, 23, 78, 22,  6, 52, 74]])

In [69]:
arr2[0:2]

array([[22, 22, 48, 70,  3, 37, 68, 57, 58, 66],
       [22,  2, 32, 76, 45, 47, 63, 78,  1, 44]])

In [70]:
arr2[0:-3]

array([[22, 22, 48, 70,  3, 37, 68, 57, 58, 66],
       [22,  2, 32, 76, 45, 47, 63, 78,  1, 44],
       [26, 63, 15, 73, 27, 62, 46, 32, 37, 43],
       [35, 43, 72, 79, 56, 44, 26, 18, 56, 23],
       [37, 67, 51,  5, 71, 30,  0, 58, 28, 61],
       [54, 29,  3, 45, 62, 27, 78, 24, 21, 69],
       [74, 62, 70, 29, 12, 68, 29, 70, 33, 63]])

In [71]:
arr2[2:-4]

array([[26, 63, 15, 73, 27, 62, 46, 32, 37, 43],
       [35, 43, 72, 79, 56, 44, 26, 18, 56, 23],
       [37, 67, 51,  5, 71, 30,  0, 58, 28, 61],
       [54, 29,  3, 45, 62, 27, 78, 24, 21, 69]])

In [72]:
arr2[1,5]

47

In [73]:
arr2[3,6]

26

In [74]:
arr2[8,-3]

54

In [75]:
arr2[7,-4]

69

In [76]:
arr2[-3,6]

69

In [77]:
arr2[-4,5] 

68

In [78]:
arr2[-5,3]

45

In [79]:
arr2[-6,7]

58

In [80]:
arr2[::-1]

array([[65, 35, 62, 44, 23, 78, 22,  6, 52, 74],
       [31,  8, 20, 52, 32, 12,  5, 54, 63, 53],
       [47, 41, 56, 39, 46, 23, 69,  6, 71, 78],
       [74, 62, 70, 29, 12, 68, 29, 70, 33, 63],
       [54, 29,  3, 45, 62, 27, 78, 24, 21, 69],
       [37, 67, 51,  5, 71, 30,  0, 58, 28, 61],
       [35, 43, 72, 79, 56, 44, 26, 18, 56, 23],
       [26, 63, 15, 73, 27, 62, 46, 32, 37, 43],
       [22,  2, 32, 76, 45, 47, 63, 78,  1, 44],
       [22, 22, 48, 70,  3, 37, 68, 57, 58, 66]])

In [81]:
arr2[::]

array([[22, 22, 48, 70,  3, 37, 68, 57, 58, 66],
       [22,  2, 32, 76, 45, 47, 63, 78,  1, 44],
       [26, 63, 15, 73, 27, 62, 46, 32, 37, 43],
       [35, 43, 72, 79, 56, 44, 26, 18, 56, 23],
       [37, 67, 51,  5, 71, 30,  0, 58, 28, 61],
       [54, 29,  3, 45, 62, 27, 78, 24, 21, 69],
       [74, 62, 70, 29, 12, 68, 29, 70, 33, 63],
       [47, 41, 56, 39, 46, 23, 69,  6, 71, 78],
       [31,  8, 20, 52, 32, 12,  5, 54, 63, 53],
       [65, 35, 62, 44, 23, 78, 22,  6, 52, 74]])

In [83]:
arr2[::2]

array([[22, 22, 48, 70,  3, 37, 68, 57, 58, 66],
       [26, 63, 15, 73, 27, 62, 46, 32, 37, 43],
       [37, 67, 51,  5, 71, 30,  0, 58, 28, 61],
       [74, 62, 70, 29, 12, 68, 29, 70, 33, 63],
       [31,  8, 20, 52, 32, 12,  5, 54, 63, 53]])

In [84]:
arr2[:2]

array([[22, 22, 48, 70,  3, 37, 68, 57, 58, 66],
       [22,  2, 32, 76, 45, 47, 63, 78,  1, 44]])

In [86]:
arr

array([0, 1, 2, 3, 4, 5])

In [87]:
arr.max()

5

In [88]:
arr.min()

0

In [89]:
arr.mean()

2.5

reashapes

In [90]:
arr.reshape(2,3)

array([[0, 1, 2],
       [3, 4, 5]])

In [92]:
arr.reshape(1,6)

array([[0, 1, 2, 3, 4, 5]])

In [93]:
arr.reshape(6,1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [94]:
arr.reshape(3,2)

array([[0, 1],
       [2, 3],
       [4, 5]])

In [98]:
row=3
col=5
row

3

In [99]:
col

5

In [102]:
[row,col]

[3, 5]

In [109]:
import math

In [120]:
math=(3,4)
math

(3, 4)

In [121]:
math[:row]

(3, 4)